# Generated by Django 5.2.17 on 2026-08-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_math_enabled'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('answer_text', models.CharField(blank=True, default='', max_length=255)),
                ('points', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_submission_per_user_quiz',
        ),
        migrations.AddField(
            model_name='score',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('user', 'quiz', 'attempt_number'), name='unique_attempt_per_user_quiz'),
        ),
        migrations.AddField(
            model_name='scoreanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quizzes.answer'),
        ),
        migrations.AddField(
            model_name='scoreanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='scoreanswer',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='scoring.score'),
        ),
        migrations.AddConstraint(
            model_name='scoreanswer',
            constraint=models.UniqueConstraint(fields=('score', 'question'), name='unique_score_answer_per_question'),
        ),
    ]
