# Generated by Django 5.2.17 on 2026-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scoreanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreanswer',
            name='correct_answer_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
