# Generated by Django 5.2.17 on 2026-09-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_scoreanswer_correct_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreanswer',
            name='answer_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scoreanswer',
            name='correct_answer_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
