# Generated by Django 5.2.17 on 2026-08-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='math_enabled',
            field=models.BooleanField(default=False, help_text='Render the question and its answers as LaTeX (via KaTeX).'),
        ),
    ]
