# Generated by Django 5.2.17 on 2026-09-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional time limit in whole minutes (1-180) for taking the quiz.', null=True),
        ),
    ]
